{
 "title": "Spring Boot example",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Main dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "http_server_requests_seconds_count",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count"
    }
   ]
  },
  {
   "title": "service_message_last_message_length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service_message_last_message_length"
    }
   ]
  },
  {
   "title": "service_message_counter_total",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "service_message_counter_total" }
   ]
  },
  {
   "title": "service_message_message_size",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "service_message_message_size" }
   ]
  },
  {
   "title": "service_message_long_operation_run_timer_seconds_max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service_message_long_operation_run_timer_seconds_max"
    }
   ]
  },
  {
   "title": "service_message_long_operation_counter_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service_message_long_operation_counter_total"
    }
   ]
  }
 ]
}